#The main workflow Actions file where instructions on push and merge into the main branch are written
name: exam-project-2
on: 
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  check-format-on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
        ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x" 

      - name: Install Dependencies
        run: npm ci

      - name: Check Format
        run: npm run check-format-on-pull-request

      - name: Print message
        run: echo "{{ github.actor }} is doing a pull request into the main branch"

