#The main workflow Actions file where instructions on push and merge into the main branch are written
name: Version and Tag on Merge 
on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  version-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16.x" 

      - name: Install Dependencies
        run: npm ci

      - name: Bump minor version and create tag after merge
        run: | 
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          npm version minor -m "chore(release): cut the minor release %s"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push tag and changes 
        run: git push origin HEAD:${{ github.ref }} --tags 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
