#This workflow YML file are doing a job when a pull request is opend and ned a review from the owner to finish
name: Format and Check on Pull Request
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  check-format-on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: npm ci

      - name: Check Format
        run: npm run check-format-on-pull-request

      - name: Print message
        run: echo "${{ github.actor }} is doing a pull request into the main branch"

